newspaper/urls.py
from django.urls import path

from newspaper.views import (
    index,
    TopicListView,
    TopicCreateView,
    TopicUpdateView,
    TopicDeleteView,
    NewspaperListView,
    NewspaperDetailView,
    NewspaperCreateView,
    NewspaperUpdateView,
    NewspaperDeleteView,
    RedactorsListView,
    RedactorsDetailView,
    RedactorsCreateView,
    RedactorUpdateView,
    RedactorsDeleteView,
    assign_redactor_to_newspaper,

)

urlpatterns = [
    path("", index, name="index"),
    path("topics/", TopicListView.as_view(), name="topics-list"),
    path("topics/create/", TopicCreateView.as_view(), name="topics-create"),
    path("topics/<int:pk>/update/", TopicUpdateView.as_view(), name="topics-update"),
    path("topics/<int:pk>/delete/", TopicDeleteView.as_view(), name="topics-delete"),
    path("newspaper/", NewspaperListView.as_view(), name="newspaper-list"),
    path("newspapers/<int:pk>/", NewspaperDetailView.as_view(), name="newspaper-detail"),
    path("newspaper/create/", NewspaperCreateView.as_view(), name="newspaper-create"),
    path("newspaper/<int:pk>/update/", NewspaperUpdateView.as_view(), name="newspaper-update"),
    path("newspaper/<int:pk>/delete/", NewspaperDeleteView.as_view(), name="newspaper-delete"),
    path("redactors/", RedactorsListView.as_view(), name="redactors-list"),
    path("redactors/<int:pk>/", RedactorsDetailView.as_view(), name="redactors-detail"),
    path("redactors/create/", RedactorsCreateView.as_view(), name="redactors-create"),
    path("redactors/<int:pk>/update/", RedactorUpdateView.as_view(), name="redactors-update"),
    path("redactors/<int:pk>/delete/", RedactorsDeleteView.as_view(), name="redactors-delete"),
    path(
        "redactors/<int:pk>/assign/",
        assign_redactor_to_newspaper,
        name="assign-redactor"
    )
]
app_name = "newspaper"

newspaper_agency/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("newspaper.urls"), name="newspaper"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

templates/includes/footer.html
<footer class="footer pt-1 mt-3 text-center">
  <hr class="horizontal dark mb-5">
  <div class="container">
    <div class="row justify-content-center">
      <div class="align-items-center">
        <div>
          <h6 class="text-gradient text-primary text-dark align-items-center font-weight-bolder">Newspaper Agency System</h6>
        </div>
        <div>
          <h6 class="mt-3 mb-2 opacity-8">Social Media</h6>
          <ul class="d-flex flex-row ms-n3 nav justify-content-center">
            <li class="nav-item">
              <a class="nav-link pe-1" href="https://www.facebook.com/CreativeTim/" target="_blank">
                <i class="fab fa-facebook text-lg opacity-8"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link pe-1" href="https://twitter.com/creativetim" target="_blank">
                <i class="fab fa-twitter text-lg opacity-8"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link pe-1" href="https://dribbble.com/creativetim" target="_blank">
                <i class="fab fa-dribbble text-lg opacity-8"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link pe-1" href="https://github.com/creativetimofficial" target="_blank">
                <i class="fab fa-github text-lg opacity-8"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link pe-1" href="https://www.youtube.com/channel/UCVyTG4sCw-rOvB9oHkzZD1w" target="_blank">
                <i class="fab fa-youtube text-lg opacity-8"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>

templates/includes/navigation-auth.html
<div class="container position-sticky z-index-sticky top-0">   
  <div class="row">
    <div class="col-12">
      <nav class="navbar navbar-expand-lg  blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
        <div class="container-fluid">
          <a class="navbar-brand font-weight-bolder ms-sm-3" 
             href="/" rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom">
            Newspaper Agency System
          </a>
          <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon mt-2">
              <span class="navbar-toggler-bar bar1"></span>
              <span class="navbar-toggler-bar bar2"></span>
              <span class="navbar-toggler-bar bar3"></span>
            </span>
          </button>
          <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0" id="navigation">
            <ul class="navbar-nav navbar-nav-hover ms-lg-12 ps-lg-5 w-100">
              <li class="nav-item ms-lg-auto">
                <a class="nav-link nav-link-icon me-2" 
                   href="https://appseed.us/support/" target="_blank">
                  <i class="fa fa-rocket me-1"></i>
                  <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Get Free Support">Support</p>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>
  </div>
</div>

templates/includes/navigation-light.html
<nav class="navbar navbar-expand-lg navbar-light bg-white py-3">
    <div class="container">
      <a class="navbar-brand" href="/" rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom">
        Newspaper Agency System
      </a>
      <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon mt-2">
          <span class="navbar-toggler-bar bar1"></span>
          <span class="navbar-toggler-bar bar2"></span>
          <span class="navbar-toggler-bar bar3"></span>
        </span>
      </button>
       <a class="btn btn-sm  bg-secondary text-white btn-round mb-0 me-1 mt-2 mt-md-0"
         href="{% url 'newspaper:index' %}">Go back
      </a>
      <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 ms-lg-12 ps-lg-5" id="navigation">
        <ul class="navbar-nav navbar-nav-hover w-100">
          <li class="nav-item ms-lg-auto">
            <a class="nav-link nav-link-icon me-2" href="{% url 'logout' %}">
              <i class="fa fa-sign-out me-1"></i>
              <p class="d-inline text-sm z-index-1 font-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Logout">Logout</p>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  

templates/includes/navigation-transparent.html
<div class="container position-sticky z-index-sticky top-0">
  <div class="row">
    <div class="col-12">
      <nav class="navbar navbar-expand-lg  blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
        <div class="container-fluid">
          <a class="navbar-brand font-weight-bolder ms-sm-3" 
             href="/" rel="tooltip" title="Newspaper Agency System" data-placement="bottom">
            Newspaper Agency System
          </a>
          <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon mt-2">
              <span class="navbar-toggler-bar bar1"></span>
              <span class="navbar-toggler-bar bar2"></span>
              <span class="navbar-toggler-bar bar3"></span>
            </span>
          </button>
          <a class="btn btn-sm  bg-white  btn-round mb-0 me-1 mt-2 mt-md-0" 
             href="{% url 'newspaper:index' %}">Go back
          </a>
          <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0" id="navigation">
            <ul class="navbar-nav navbar-nav-hover ms-lg-12 ps-lg-5 w-100">
              <li class="nav-item ms-lg-auto">
                <a class="nav-link nav-link-icon me-2" href="{% url 'logout' %}">
                  <i class="fa fa-sign-out me-1"></i>
                  <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Logout">Logout</p>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>
  </div>
</div>

templates/includes/navigation.html
<div class="container position-sticky z-index-sticky top-0">
  <div class="row">
    <div class="col-12">
      <nav class="navbar navbar-expand-lg  blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
        <div class="container-fluid">
          <a class="navbar-brand font-weight-bolder ms-sm-3" 
             href="/" rel="tooltip" title="Newspaper Agency System" data-placement="bottom">
            Newspaper Agency System
          </a>
          <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon mt-2">
              <span class="navbar-toggler-bar bar1"></span>
              <span class="navbar-toggler-bar bar2"></span>
              <span class="navbar-toggler-bar bar3"></span>
            </span>
          </button>
          <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0" id="navigation">
            <ul class="navbar-nav navbar-nav-hover ms-lg-12 ps-lg-5 w-100">
              <li class="nav-item ms-lg-auto">
                <a class="nav-link nav-link-icon me-2" href="{% url 'logout' %}">
                  <i class="fa fa-sign-out me-1"></i>
                  <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Logout">Logout</p>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>
  </div>
</div>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="{% query_transform request page=page_obj.previous_page_number %}">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="{% query_transform request page=page_obj.next_page_number %}">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/scripts.html
  <script src="{{ ASSETS_ROOT }}/js/core/popper.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/core/bootstrap.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/perfect-scrollbar.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/prism.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/parallax.min.js"></script>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}
    <li class="list-group-item">User: <a href="{{ user.get_absolute_url }}">{{ user.get_username }}</a></li>
    <li class="list-group-item"><a href="{% url 'logout' %}?next={{request.path}}">Logout</a></li>
  {% else %}
    <li class="list-group-item"><a href="{% url 'login' %}?next={{request.path}}">Login</a></li>
  {% endif %}

  <br>

  <li class="list-group-item"><a href="{% url 'newspaper:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'newspaper:newspaper-list' %}">Newspapers</a></li>
  <li class="list-group-item"><a href="{% url 'newspaper:redactors-list' %}">Redactors</a></li>
  <li class="list-group-item"><a href="{% url 'newspaper:topics-list' %}">Topics</a></li>
</ul>