newspaper/urls.py
from django.urls import path

from newspaper.views import (
    index,
    TopicListView,
    TopicCreateView,
    TopicUpdateView,
    TopicDeleteView,
    NewspaperListView,
    NewspaperDetailView,
    NewspaperCreateView,
    NewspaperUpdateView,
    NewspaperDeleteView,
    RedactorsListView,
    RedactorsDetailView,
    RedactorsCreateView,
    RedactorUpdateView,
    RedactorsDeleteView,
    assign_redactor_to_newspaper,

)

urlpatterns = [
    path("", index, name="index"),
    path("topics/", TopicListView.as_view(), name="topics-list"),
    path("topics/create/", TopicCreateView.as_view(), name="topics-create"),
    path("topics/<int:pk>/update/", TopicUpdateView.as_view(), name="topics-update"),
    path("topics/<int:pk>/delete/", TopicDeleteView.as_view(), name="topics-delete"),
    path("newspaper/", NewspaperListView.as_view(), name="newspaper-list"),
    path("newspapers/<int:pk>/", NewspaperDetailView.as_view(), name="newspaper-detail"),
    path("newspaper/create/", NewspaperCreateView.as_view(), name="newspaper-create"),
    path("newspaper/<int:pk>/update/", NewspaperUpdateView.as_view(), name="newspaper-update"),
    path("newspaper/<int:pk>/delete/", NewspaperDeleteView.as_view(), name="newspaper-delete"),
    path("redactors/", RedactorsListView.as_view(), name="redactors-list"),
    path("redactors/<int:pk>/", RedactorsDetailView.as_view(), name="redactors-detail"),
    path("redactors/create/", RedactorsCreateView.as_view(), name="redactors-create"),
    path("redactors/<int:pk>/update/", RedactorUpdateView.as_view(), name="redactors-update"),
    path("redactors/<int:pk>/delete/", RedactorsDeleteView.as_view(), name="redactors-delete"),
    path(
        "redactors/<int:pk>/assign/",
        assign_redactor_to_newspaper,
        name="assign-redactor"
    )
]
app_name = "newspaper"

newspaper_agency/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("newspaper.urls"), name="newspaper"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

newspaper/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class Topic(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self) -> str:
        return self.name


class Redactor(AbstractUser):
    years_of_experience = models.IntegerField(default=0)

    class Meta:
        ordering = ["username"]

    def __str__(self) -> str:
        return f"{self.username}: {self.first_name} {self.last_name}"

    def get_absolute_url(self):
        return reverse("newspaper:redactors-detail", kwargs={"pk": self.pk})


class Newspaper(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    published_date = models.DateTimeField(auto_now=True)
    topic = models.ForeignKey(
        Topic,
        on_delete=models.CASCADE,
        related_name="topics"
    )
    publishers = models.ManyToManyField(
        Redactor,
        related_name="newspapers"
    )

    class Meta:
        ordering = ["title"]

    def __str__(self) -> str:
        return self.title

newspaper/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


from newspaper.models import Redactor, Newspaper


class NewspaperForm(forms.ModelForm):
    publishers = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Newspaper
        fields = "__all__"


class RedactorCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Redactor
        fields = UserCreationForm.Meta.fields + (
            "username",
            "first_name",
            "last_name",
            "years_of_experience",
        )


class RedactorUpdateForm(forms.ModelForm):
    class Meta:
        model = Redactor
        fields = [
            "username",
            "first_name",
            "last_name",
            "years_of_experience"
        ]


class NewspaperSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search newspaper by title"
            }
        )
    )


class TopicSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search topic by name"
            }
        )
    )


class RedactorsSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search redactors by username"
            }
        )
    )

newspaper/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from newspaper.models import Topic, Redactor, Newspaper
from newspaper.forms import (
    NewspaperForm,
    RedactorCreationForm,
    RedactorUpdateForm,
    NewspaperSearchForm,
    RedactorsSearchForm,
    TopicSearchForm
)


@login_required
def index(request: HttpRequest) -> HttpResponse:
    num_topic = Topic.objects.count()
    num_redactor = Redactor.objects.count()
    num_newspaper = Newspaper.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_topic": num_topic,
        "num_redactor": num_redactor,
        "num_newspaper": num_newspaper,
        "num_visits": num_visits + 1,
    }

    return render(request, "newspaper/index.html", context=context)


class TopicListView(LoginRequiredMixin, generic.ListView):
    model = Topic
    context_object_name = "topics_list"
    template_name = "newspaper/topics_list.html"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TopicListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_field"] = TopicSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = Topic.objects.all()
        form = TopicSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class TopicCreateView(LoginRequiredMixin, generic.CreateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("newspaper:topics-list")


class TopicUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("newspaper:topics-list")


class TopicDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Topic
    success_url = reverse_lazy("newspaper:topics-list")


class NewspaperListView(LoginRequiredMixin, generic.ListView):
    model = Newspaper,
    context_object_name = "newspaper_list"
    template_name = "newspaper/newspaper_list.html"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(NewspaperListView, self).get_context_data(**kwargs)
        title = self.request.GET.get("title", "")
        context["search_field"] = NewspaperSearchForm(
            initial={"title": title}
        )
        return context

    def get_queryset(self):
        queryset = Newspaper.objects.all()
        form = NewspaperSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(title__icontains=form.cleaned_data["title"])
        return queryset


class NewspaperCreateView(LoginRequiredMixin, generic.CreateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("newspaper:newspaper-list")


class NewspaperDetailView(LoginRequiredMixin, generic.DetailView):
    model = Newspaper


class NewspaperUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("newspaper:newspaper-list")


class NewspaperDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Newspaper
    success_url = reverse_lazy("newspaper:newspaper-list")


class RedactorsListView(LoginRequiredMixin, generic.ListView):
    model = Redactor
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(RedactorsListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["search_field"] = RedactorsSearchForm(
            initial={"username": username}
        )
        return context

    def get_queryset(self):
        queryset = Redactor.objects.all()
        form = RedactorsSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )
        return queryset


class RedactorsDetailView(LoginRequiredMixin, generic.DetailView):
    model = Redactor
    queryset = Redactor.objects.prefetch_related("newspapers__topic")


class RedactorsCreateView(LoginRequiredMixin, generic.CreateView):
    model = Redactor
    form_class = RedactorCreationForm
    success_url = reverse_lazy("newspaper:redactors-list")


class RedactorUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Redactor
    form_class = RedactorUpdateForm
    success_url = reverse_lazy("newspaper:redactors-list")


class RedactorsDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Redactor
    success_url = reverse_lazy("newspaper:redactors-list")


@login_required
def assign_redactor_to_newspaper(request, pk):
    redactor = Redactor.objects.get(id=request.user.id)
    if (
        Newspaper.objects.get(id=pk) in redactor.newspapers.all()
    ):
        redactor.newspapers.remove(pk)
    else:
        redactor.newspapers.add(pk)
    return HttpResponseRedirect(reverse_lazy("newspaper:newspaper-detail", args=[pk]))

templates/newspaper/newspaper_confirm_delete.html
{% extends 'layouts/base.html' %}

{% block title %} Delete page {% endblock title %}

{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %}{% endblock body_class %}

{% block content %}

  {% include "includes/navigation-light.html" %}

  <header xmlns="http://www.w3.org/1999/html">
    <div class="page-header section-height-85">
      <div>
        <img class="position-absolute fixed-top ms-auto w-50 h-100 z-index-0 
        d-none d-sm-none d-md-block border-radius-section border-top-end-radius-0 
        border-top-start-radius-0 border-bottom-end-radius-0" alt="" src="{{ ASSETS_ROOT }}/img/TNY.jpg">
      </div>
      <div class="container">
        <div class="row">
          <div class="col-lg-7 d-flex justify-content-center flex-column">
            <div class="card d-flex blur justify-content-center p-4 shadow-lg my-sm-0 my-sm-6 mt-8 mb-5">
              <div class="text-center">
                <h3 class="text-gradient text-primary text-dark">Do you want to delete this newspaper?</h3>
                <p class="mb-0">
                  If you delete this newspaper, all information will be not available anymore.
                </p>
              </div>
                <form role="form" id="contact-form" method="post" autocomplete="off">
                {% csrf_token %}
                  <div class="col-md-12 d-flex justify-content-between">
                    <input type="submit" value="Yes" class="btn btn-danger">
                    
                    <div class="col-md-3 text-right">
                      <a class="btn btn-success" href="{% url 'newspaper:newspaper-detail' pk=newspaper.id %}">
                      Cancel
                    </a>
                    </div>
                  </div>
                </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>

{% endblock content %}
 
{% block javascripts %}

  <script src="{{ ASSETS_ROOT }}/js/soft-design-system.min.js?v=1.0.1" type="text/javascript"></script>

{% endblock javascripts %}

templates/newspaper/newspaper_detail.html
{% extends 'layouts/base.html' %}

{% block title %} Newspaper detail {% endblock title %}


{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} blog-author bg-gray-100 {% endblock body_class %}

{% block content %}

  {% include "includes/navigation-light.html" %}

  <section class="py-sm-7 py-5 position-relative">
    <div class="page-header section-height-85">
        <div>
          <img class="position-absolute fixed-top ms-auto w-45 h-100 z-index-0
        d-none d-sm-none d-md-block border-radius-section border-top-end-radius-0 
        border-top-start-radius-0 border-bottom-end-radius-0" src="{{ ASSETS_ROOT }}/img/TNY.jpg" alt="">
        </div>
    <div class="container">
      <div class="row">
        <div class="col-12 mx-auto">
            <div class="col-lg-7 col-md-7 z-index-2 position-relative px-md-2 px-sm-5 mt-sm-0 mt-4">
              <div class="d-flex justify-content-between align-items-center mb-2">
                <h1 class="mb-0">
                  Title: {{ newspaper.title }}
                  <br>
                    <a class="btn bg-gradient-danger text-white mt-3 mb-0" 
                       href="{% url 'newspaper:newspaper-delete' pk=newspaper.id %}">
                      Delete
                    </a>
                    
                    <a class="btn bg-gradient-success mt-3 mb-0" 
                       href="{% url 'newspaper:newspaper-update' pk=newspaper.id %}">
                      Update
                    </a>
                </h1>
              </div>
              <p style="max-width: 800px; margin: 0 auto;">
                <h2>Content:</h2> {{ newspaper.content }}
                <br><a href="javascript:" class="text-info icon-move-right">More
                    <i class="fas fa-arrow-right text-sm ms-1"></i>
                  </a>
                <h2>Topics:</h2>
              {% for topic in newspaper.topic.all %}
                <li>{{ newspaper.topic.name }}</li>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
  </div>
  </section>
  <section class="py-1">
    <div class="container">
      <div class="row">
        <div class="col-lg-6">
          <div class="mb-1">
            <h1>List of redactors:</h1>
              {% if newspaper in user.newspapers.all %}
                <a href="{% url 'newspaper:assign-redactor' pk=newspaper.id %}" 
                   class="btn btn-danger link-to-page">
                  Delete me from this newspaper
                </a>
              {% else %}
                <a href="{% url 'newspaper:assign-redactor' pk=newspaper.id %}" 
                   class="btn btn-success link-to-page">
                  Assign me to this newspaper
                </a>
              {% endif %}
                <hr>
              {% for redactor in newspaper.publishers.all %}
                <li>{{ redactor.username }} ({{ redactor.first_name }} {{ first_name.last }})</li>
              {% endfor %}
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-3 col-sm-6">
          <div class="card card-plain card-blog">
            <div class="card-image border-radius-lg position-relative">
            </div>
            <div class="card-body px-0">
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  
{% endblock content %}

{% block javascripts %}

  <script src="{{ ASSETS_ROOT }}/js/soft-design-system.min.js?v=1.0.1" type="text/javascript"></script>

{% endblock javascripts %}

templates/newspaper/newspaper_list.html
{% extends 'layouts/base.html' %}

{% block title %} Newspapers List {% endblock title %}


{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %}{% endblock body_class %}

{% block content %}

  {% include "includes/navigation-transparent.html" %}
  {% load crispy_forms_filters %}

  <header class="bg-gradient-dark">
    <div class="page-header section-height-75" style="background-image: url('{{ ASSETS_ROOT }}/img/newspapers.jpg')">
      <span class="mask bg-gradient-info opacity-8"></span>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8 text-center mx-auto my-auto">
            <h1 class="text-white">List of newspaper</h1>
            <p class="lead mb-4 text-white opacity-8"> You can create newspapers on this page.
            </p>
            <a type="submit" 
               href="{% url 'newspaper:newspaper-create' %}" 
               class="btn bg-white text-dark"> Create newspaper
            </a>
            
          </div>
        </div>
      </div>
      <div class="position-absolute w-100 z-index-1 bottom-0">
        <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto">
          <defs>
            <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z"></path>
          </defs>
          <g class="moving-waves">
            <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(255,255,255,0.40"></use>
            <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.35)"></use>
            <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.25)"></use>
            <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)"></use>
            <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)"></use>
            <use xlink:href="#gentle-wave" x="48" y="16" fill="rgba(255,255,255,1"></use>
          </g>
        </svg>
      </div>
    </div>
  </header>
   
  <form action="" method="get" class="form-inline">
    {{ search_field|crispy }}
    <input class="btn bg-gradient-faded-secondary text-dark" type="submit" value="🔍">
  </form>
  
  {% if newspaper_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Topic</th>
      </tr>
      {% for newspaper in newspaper_list %}
        <tr>
          <td>
            <a href="{% url "newspaper:newspaper-detail" pk=newspaper.id %}">{{ newspaper.id }}</a>
          </td>
          <td>{{ newspaper.title }}</td>
          <td>{{ newspaper.topics.name }}</td>
        </tr>
        {% endfor %}
  {% else %}
    <p>There are no newspaper in list</p>
  {% endif %}
    </table>
{% endblock content %}

templates/newspaper/redactor_detail.html
{% extends 'layouts/base.html' %}

{% block title %} Author {% endblock title %}

{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} blog-author bg-black-100 {% endblock body_class %}

{% block content %}

  {% include "includes/navigation-light.html" %}
  
  <section class="py-sm-7 py-5 position-relative" xmlns="http://www.w3.org/1999/html">
    <section class="container">
      <section class="row">
        <section class="col-12 mx-auto">
          <section class="row py-lg-7 py-5">
            <div class="col-lg-3 col-md-5 position-relative my-auto">
              <img class="img border-radius-lg max-width-200 w-100 position-relative z-index-2"
                   src="{{ ASSETS_ROOT }}/img/r1.jpg" alt="">
            </div>
            <div class="col-lg-7 col-md-7 z-index-2 position-relative px-md-2 px-sm-5 mt-sm-0 mt-4">
              <h1>Redactor's details</h1>
              <div class="d-flex justify-content-between align-items-center mb-2">
                <h4 class="mb-0">{{ redactor.first_name }} {{ redactor.last_name }}</h4>
                <div class="d-block">
                  <a class="btn bg-gradient-success text-white mt-3 mb-0" 
                       href="{% url 'newspaper:redactors-update' pk=redactor.id %}">
                      Update
                  </a>
                  <a class="btn bg-gradient-danger text-white mt-3 mb-0" 
                       href="{% url 'newspaper:redactors-delete' pk=redactor.id %}">
                      Delete
                  </a>
                </div>
              </div>
              <div class="row mb-4">
                <div class="col-auto">
                  <span>Username:</span>
                  <span class="h6">{{ redactor.username }}</span>
                </div>
                <div class="col-auto">
                  <span>Years of experience:</span>
                  <span class="h6">{{ redactor.years_of_experience }}</span>
                </div>
              <p class="text-lg mb-3">
                <h4>Newspapers</h4>
                  {% if newspapers_list %}
                    <ul>
                      {% for newspaper in newspapers_list %}
                        <li>
                          <p><strong>Title:</strong> {{ newspaper.title }}</p>
                          <p><strong>Content:</strong> {{ newspaper.content }}</p>
                          <p><strong>Published date:</strong> {{ newspaper.published_date }}</p>
                          <p class="text-muted"><strong>Id:</strong> {{ newspaper.id }}</p>
                        </li>
                      {% endfor %}
                    </ul>
                  {% else %}
                    <p>There are no newspapers in the list</p>
                  {% endif %}
            </div>
          </div>
        </section>
      </section>
    </section>
  </section>
    
{% endblock content %}

{% block javascripts %}

  <script src="{{ ASSETS_ROOT }}/js/soft-design-system.min.js?v=1.0.1" type="text/javascript"></script>

{% endblock javascripts %}

templates/newspaper/redactor_list.html
{% extends 'layouts/base.html' %}

{% block title %} Redactor's list {% endblock title %}


{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} Redactor's list {% endblock body_class %}

{% block content %}

  {% include "includes/navigation-transparent.html" %}
  {% load crispy_forms_filters %}

  <header class="bg-gradient-dark">
    <div class="page-header section-height-75" style="background-image: url('{{ ASSETS_ROOT }}/img/redactors.jpeg');">
      <span class="mask bg-gradient-info opacity-8"></span>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8 text-center mx-auto my-auto">
            <h1 class="text-white">List of redactors</h1>
            <p class="lead mb-4 text-white opacity-8">You can create a new redactor on this page.
            </p>
            <a type="submit" 
               href="{% url 'newspaper:redactors-create' %}" 
               class="btn bg-white text-dark">Create Redactor
            </a>
          </div>
        </div>
      </div>
      <div class="position-absolute w-100 z-index-1 bottom-0">
        <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto">
          <defs>
            <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z"></path>
          </defs>
          <g class="moving-waves">
            <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(255,255,255,0.40"></use>
            <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.35)"></use>
            <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.25)"></use>
            <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)"></use>
            <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)"></use>
            <use xlink:href="#gentle-wave" x="48" y="16" fill="rgba(255,255,255,1"></use>
          </g>
        </svg>
      </div>
    </div>
  </header>
  
  <form method="get" action="" class="form-inline">
        {{ search_field|crispy }}
        <input class="btn btn-secondary" type="submit" value="🔍">
    </form>

    {% if redactor_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Username</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Years of experience</th>
      </tr>
    {% for redactor in redactor_list %}
      <tr>
        <td>{{ redactor.id }}</td>
        <td>
          <a href="{{ redactor.get_absolute_url }}">
            {{ redactor.username }} {% if user == redactor %} (Me){% endif %}
          </a>
        </td>
        <td>{{ redactor.first_name }}</td>
        <td>{{ redactor.last_name }}</td>
        <td>{{ redactor.years_of_experience }}</td>
      </tr>
    {% endfor %}

    </table>
    {% else %}
      <p>There are no redactors in the newspaper.</p>
    {% endif %}
  
{% endblock content %}

templates/newspaper/topics_list.html
{% extends 'layouts/base.html' %}

{% block title %} Topics List {% endblock title %}

{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} topic_list {% endblock body_class %}

{% block content %}

  {% include "includes/navigation-transparent.html" %}
  {% load crispy_forms_filters %}
  
  <header class="bg-gradient-dark">
    <div class="page-header section-height-75" style="background-image: url('{{ ASSETS_ROOT }}/img/newspapers.jpg');">
      <span class="mask bg-gradient-info opacity-8"></span>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8 text-center mx-auto my-auto">
            <h1 class="text-white">List of topics</h1>
            <p class="lead mb-4 text-white opacity-8"> You can create a new topic on this page.
            </p>
            <a type="submit" 
               href="{% url 'newspaper:topics-create' %}" 
               class="btn bg-white text-dark">Create Topic
            </a>
            
          </div>
        </div>
      </div>
      <div class="position-absolute w-100 z-index-1 bottom-0">
        <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto">
          <defs>
            <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z"></path>
          </defs>
          <g class="moving-waves">
            <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(255,255,255,0.40"></use>
            <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.35)"></use>
            <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.25)"></use>
            <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)"></use>
            <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)"></use>
            <use xlink:href="#gentle-wave" x="48" y="16" fill="rgba(255,255,255,1"></use>
          </g>
        </svg>
      </div>
    </div>
  </header>
  
  <form action="" method="get" class="form-inline">
    {{ search_field|crispy }}
    <input class="btn bg-white text-dark" type="submit" value="🔍">
  </form>
  
  {% if topics_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for topic in topics_list %}
        <tr>
          <td>
            {{ topic.id }}
          </td>
          <td>
            {{ topic.name }}
          </td>
          <td>
              <a type="submit"
                  href="{% url 'newspaper:topics-update' pk=topic.id %}"
                  class="btn bg-gradient-success text-white">Update
              </a>
            </td>
            <td>
              <a type="submit" 
               href="{% url 'newspaper:topics-delete' pk=topic.id %}" 
               class="btn bg-gradient-danger text-white">Delete
              </a>
            </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
      <p>There are no topics in the list.</p>
  {% endif %}
  
{% endblock content %}